### ISSUE TITLE
Man må ikke blive sprunget over 2 gange i træk

### ISSUE THREAD

**Issue by tarcom** [tarcom/NykreditBF#1]
Lav ny algoritme...

**Comment by tarcom** [comment]
@RobbingDaHood arbejder på denne, ved at lave en tuneringsplans algoritme

**Comment by nlkolbe** [comment]
Allan, jeg overvejer at kigge lidt på koden omkring generering af hold ift følgende:
- Der bliver kigget på hvem der lige har spillet, og vil være præference for at sikre kampe til folk der evt ikke var med i de seneste runder
- Der vil blive kigget et par runder tilbage, og vil blive forsøgt undgået at der spilles med par af spillere, der lige har dannet par

Skal jeg kaste mig over det? (Daniels kode vil umiddelbart blive lavet til at lave en turnering fra starten, ikke til disse ad-hoc kampe) 

Nikolaj

**Comment by nlkolbe** [comment]
Hmmm, Daniel har lige oprettet https://github.com/tarcom/NykreditBF/issues/7 så jeg venter foreløbigt med at gøre noget :-)

**Comment by RobbingDaHood** [comment]
Jeg oprettede bare #7 fordi nogen kunne lave det på et tidspunkt, det gør jeg ikke lige nu. 

Derudover tænker jeg at man kunne implementere en metode til at vælge sin "kamp generations"-algoritme. 

Så kunne man jo have en frokost algoritme, FKA++, Tunerings algoritme osv. (jeg tænker en drop down hvor man selv vælger hvad man ønsker) :)

**Comment by RobbingDaHood** [comment]
Fixed by #10

**Comment by tarcom** [comment]
Weee!!! :)

**Comment by RobbingDaHood** [comment]
@tarcom  skal du ikke markere den her done :)

**Comment by tarcom** [comment]
Jo da :)
