### ISSUE TITLE
Når der spilles 2 mod 1, skal der være alternativ point givning

### ISSUE THREAD

**Issue by tarcom** [tarcom/NykreditBF#3]
Måske skal det være således at ham der er alene kan vinde 2 point fra hver (altså default intense), mens de to aldrig kan vinde points (da det er for let), men kun skal undgå at tabe...

**Comment by nlkolbe** [comment]
Hvis man gennemfører ovenstående, er der så overhovedet motivation for de to personer til at spille en kamp mod den ene i f.eks. en pause?

**Comment by RobbingDaHood** [comment]
Nej, men nogen gange er man uheldig :) 

Jeg vil sige at miste 2 point er motivation nok til ikke at tabe :)

**Comment by nlkolbe** [comment]
Daniel, jeg er usikker på om din kommentar gælder den nuværende situation eller den Allan foreslår? :-)

**Comment by RobbingDaHood** [comment]
Den Allan foreslår :) 

Det er ikke fair at få nogen point, hvis man var 2 mod 1: Men det er godt nok slemt hvis man taber 2 mod 1 :)

**Comment by RobbingDaHood** [comment]
#15  Hvis man er alene så får man alle de point modstanderne mistede.

**Comment by tarcom** [comment]
det lyder til at denne kan lukkes efter @RobbingDaHood nye release
